name: Publish to GDS IDEA PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    uses: co-cddo/gds-idea-workflows-catalogue/.github/workflows/gds_idea_pypi_publish.yml@main
    secrets: inherit
